name: CI

on: [push, pull_request]

jobs:
  test:
    name: Running Tests
    strategy:
      fail-fast: false
      matrix:
        python: ["3.6"]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install sk-typing
        run: pip install -e ".[dev]"

      # - name: Run linter
      #   run: mypy sk_typing

      - name: Run pytest
        run: pytest
