name: CI

on: [push, pull_request]

jobs:
  test:
    name: Running Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install sk-typing
        run: pip install -e ".[dev]"

      - name: Run pytest
        run: pytest
